site_name: geoserverx
theme:
  name: material
  palette:
    primary: green
  features:
    - content.code.copy
repo_url: https://github.com/geobeyond/geoserverx

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences