site_name: geoserverx
site_description: "geoserverx is a modern python and CLI package for communicating with Geoserver."
site_url: https://geobeyond.github.io/geoserverx/
site_author: Geobeyond
copyright: "&copy; 2024 Geobeyond"
theme:
  name: material
  icon:
    logo: material/package-variant
    favicon: material/package-variant
  palette:
    primary: white
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
repo_url: https://github.com/geobeyond/geoserverx
plugins:
  - social
  - search
nav:
  - Home: index.md
  - Docs:
      - pages/docs/index.md
      - Workspaces: pages/docs/workspace.md
      - Vector Data: pages/docs/vector-store.md
      - Raster Data: pages/docs/raster-store.md
      - Style: pages/docs/style.md
      - Example: pages/docs/example.md
  # - Async:
  #     - pages/async/index.md
  #     - Workspaces: pages/async/workspace.md
  #     - Vector Data: pages/async/vector-store.md
  #     - Raster Data: pages/async/raster-store.md
  #     - Style: pages/async/style.md
  #     - Example: pages/async/example.md
  # - Command Line:
  #     - pages/cli/index.md
  #     - Workspaces: pages/cli/workspace.md
  #     - Vector Data: pages/cli/vector-store.md
  #     - Raster Data: pages/cli/raster-store.md
  #     - Style: pages/cli/style.md
  #     - Example: pages/cli/example.md
markdown_extensions:
  - meta # option to add some meta tags on top, title, author, date, etc
  - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
  - pymdownx.details # advanced collapsible panels
  - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
  - footnotes # notes bottom of page
  - attr_list # used to size images
  - md_in_html # used to size images
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  # pygeoapi primary color with light and dark variations from material.io
  # https://material.io/resources/color/#!/?view.left=0&view.right=1
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/termynal.js
  - assets/javascripts/custom.js

extra:
  generator: false
