site_name: geoserverx
site_description: "geoserverx is a modern python and CLI package."
site_author: Geobeyond
copyright: "&copy; 2023 Geobeyond"
theme:
  name: material
  # logo: assets/images/logo.png
  palette:
    primary: green
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
repo_url: https://github.com/geobeyond/geoserverx
nav:
    - Home: index.md
    - Sync : 
      - pages/sync/index.md
      - Workspaces : pages/sync/workspace.md
      - Vector Data : pages/sync/vector-store.md
      - Raster Data : pages/sync/raster-store.md
      - Style : pages/sync/style.md
      - Example : pages/sync/example.md
    - Async : 
      - pages/async/index.md
      - Workspaces : pages/async/workspace.md
      - Vector Data : pages/async/vector-store.md
      - Raster Data : pages/async/raster-store.md
      - Style : pages/async/style.md
    - Command Line : 
      - pages/cli/index.md
      - Workspaces : pages/cli/workspace.md
      - Vector Data : pages/cli/vector-store.md
      - Raster Data : pages/cli/raster-store.md
      - Style : pages/cli/style.md
markdown_extensions:
  - meta # option to add some meta tags on top, title, author, date, etc
  - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
  - pymdownx.details # advanced collapsible panels
  - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
  - footnotes # notes bottom of page
  - attr_list # used to size images
  - md_in_html # used to size images
  - pymdownx.tabbed: 
      alternate_style: true

extra_css:
  # pygeoapi primary color with light and dark variations from material.io
  # https://material.io/resources/color/#!/?view.left=0&view.right=1
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
    - assets/javascripts/termynal.js
    - assets/javascripts/custom.js