site_name: geoserverx
site_description: "geoserverx is a modern python and CLI package."
site_author: Geobeyond
copyright: "&copy; 2023 Geobeyond"
theme:
  name: material
  palette:
    primary: green
  features:
    - content.code.copy
repo_url: https://github.com/geobeyond/geoserverx
nav:
    - Home: index.md
    - Sync : 
      - Workspaces : sync/workspace.md
      - Vector Data : sync/vector-store.md
      - Raster Data : sync/raster-store.md
      - Style : sync/style.md
markdown_extensions:
  - meta # option to add some meta tags on top, title, author, date, etc
  - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
  - pymdownx.details # advanced collapsible panels
  - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
  - footnotes # notes bottom of page
  - attr_list # used to size images
  - md_in_html # used to size images
  - pymdownx.tabbed: 
      alternate_style: true