# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "main" , "develop","develop" , "feature/**", "hotfix/**"]
  pull_request:
    branches: [ "main" , "develop"]

permissions:
  contents: read

jobs:
  test:
    name : ${{ matrix.python }} Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: "ubuntu-20.04" }
          - { python: "3.9", os: "ubuntu-20.04" }

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3.3.0

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python }}
    
    - name: Upgrade pip
      run: |
        pip install --constraint=.github/workflows/constraints.txt pip
        pip --version
    - name: Upgrade pip in virtual environments
      shell: python
      run: |
        import os
        import pip
        with open(os.environ["GITHUB_ENV"], mode="a") as io:
            print(f"VIRTUALENV_PIP={pip.__version__}", file=io)
    - name: Install Poetry
      run: |
        pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
        poetry --version
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run pytest
    
    - name: Run black
      uses: psf/black@stable
      with:
        black_args: "."
