# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "develop" , "feature/**", "hotfix/**"]
  pull_request:
    branches: [ "main" , "develop"]

permissions:
  contents: read

jobs:
  test:
    name : ${{ matrix.python }} Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python: "3.10", os: "ubuntu-20.04" }
          - { python: "3.9", os: "ubuntu-20.04" }

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    
    - name: Upgrade pip
      run: |
        pip install  pip
        pip --version
    - name: Upgrade pip in virtual environments
      shell: python
      run: |
        import os
        import pip
        with open(os.environ["GITHUB_ENV"], mode="a") as io:
            print(f"VIRTUALENV_PIP={pip.__version__}", file=io)
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run pytest

    - name: Run black
      uses: psf/black@stable

    - name: Run isort
      uses: isort/isort-action@v1
      with :
        configuration : "--profile black"
        
    - name : Ruff Check
      uses: jpetrucciani/ruff-check@main
      with:
        flags: '--fix'